# Métodos Computacionales


## Unidad 3: 

### Álgebra Lineal
- Diagonalización de una matriz
- Determinante matrical
- Inversion matricial
- Factorización LU



### Taller

**Matrices de prueba**

$$M_1= \left[ \matrix{
2 & 1 & 3 &|+ 3 \\
4 & -1 & 3 &|-4 \\ 
-1 & 5 & 5 &|+ 9
}\right]  \\ $$ 

$$ M_2=\left[ \matrix{
3 & 1 & 3 & -4 &|1 \\
6 & 4 & 8 & -10 &|5 \\ 
3 & 2 & 5 & -1 &|6 \\
-9 & 5 & -2 & -4& |2 
}\right] $$

**1**. **A**Escriba tres rutinas que realicen, dada una matriz $ A $, las operaciones anteriores sobre matrices:

**row_lamb($i$, $ \lambda $, $ A $)**: $ i $ es la fila que se va a cambiar, $ \lambda $ el factor multiplicativo y A la matriz. Esta función debería devolver la nueva matriz con la operación realizada $ (\lambda E_i) \rightarrow (E_i) $.

**row_comb ($ i $, $ j $ $ \lambda $, $ A $)**: $ i $ es la fila que se cambiará, $ j $ la fila que se agregará, $ \lambda $ el factor multiplicativo y A la matriz. Esta función debería devolver la nueva matriz con la operación realizada $ (E_i + \lambda E_j) \rightarrow (E_i) $.

**row_swap ($ i $, $ j $, $ A $)**: $ i $ y $ j $ son las filas que se intercambian. Esta función debería devolver la nueva matriz con la operación realizada $ (E_i) \leftrightarrow (E_j) $.

**B** Luego use las rutinas definidas anteriormente en el literal anterior y la funcion `Gaussian_Elimination` para resolver las matrices $M_1$ y $M_2$

In [79]:
import numpy as np
import sympy as sp

def row_lamb( i, λ, A ):
    B = A.copy()
    if isinstance(B[0,0],np.int64):
        B=B.astype(float)
    B[i] = λ*B[i]
    return B

def row_comb( i, j, λ, A ):
    B = A.copy()
    if isinstance(B[0,0],np.int64):
        B=B.astype(float)
    B[i] = λ*B[j] + B[i]
    return B

def row_swap( i, j, A ):
    B = A.copy()
    B[[i,j]] = B[[j,i]]
    return B

############################################################################################3

def Gaussian_Elimination(A0):         #Función de eliminación gaussiana
    A = 1.0*np.copy(A0)
    n=len(A)
    for i in range(n):
        for j in range(i+1):
                if i==j:
                    if A[i,j]==0:                #Si hay algún cero en la diagonal, se cambia la fila por la última
                        A = row_swap(i, -1, A)
                    break
                A = row_comb(i, j, -A[i,j]/A[j,j], A)    #Aquí se hallan lo ceros debajo de la diagonal
                 
    for i in range(n):                  #Este ciclo es para volver a hallar los ceros debajo de la diagonal si se cambió 
        for j in range(i+1):            #una fila
            if i==j:
                if A[i,j]==0:
                    A = row_swap(i, -1, A)
                break
            A = row_comb(i, j, -A[i,j]/A[j,j], A)
    return A

################################################

def Sol(A0):
    A = 1.0*np.copy(A0)
    n = len(A)
    for i in range(n):
        for j in range(i+1):
                if i==j:
                    if A[i,j]==0:
                        A = row_swap(i, -1, A)
                    break
                A = row_comb(i, j, -A[i,j]/A[j,j], A)
    for i in range(n):
        for j in range(i+1):
                if i==j:
                    if A[i,j]==0:
                        A = row_swap(i, -1, A)
                    break
                A = row_comb(i, j, -A[i,j]/A[j,j], A)  #Gaussian_Elimination
    x = np.zeros(n)                                    #se hace un vector para las soluciones
    if A[n-1, n]==1:                                   #Se normaliza el ultimo elemento de la diagonal si es diferente de 1
        x[n-1] = A[n-1,n]
    else:
        A = row_lamb(i, 1/A[n-1,n-1], A)
        x[n-1] = A[n-1,n]
        
    for i in range( n-1, -1, -1 ):
        x[i] = ( A[i,n] - sum(A[i,i+1:n]*x[i+1:n]) )/A[i,i]
    
    return A, x

############################################################################################

M1 = np.array([[2, 1, 3, 3],
              [4, -1, 3, -4],
              [-1, 5, 5, 9]])

M2 = np.array([[3, 1, 3, -4, 1],
              [6, 4, 8, -10, 5],
              [3, 2, 5, -1, 6],
              [-9, 5, -2, -4, 2]])

A1, x1 = Sol(M1)
A2, x2 = Sol(M2)
print('Matriz escalonada:\n {} \n Solución del sistema:\n{} '.format(A1, x1))
print('Matriz escalonada:\n {} \n Solución del sistema:\n {}'.format(A2, x2))

Matriz escalonada:
 [[  2.           1.           3.           3.        ]
 [  0.          -3.          -3.         -10.        ]
 [  0.           0.           1.          -7.83333333]] 
 Solución del sistema:
[ 7.66666667 11.16666667 -7.83333333] 
Matriz escalonada:
 [[ 3.     1.     3.    -4.     1.   ]
 [ 0.     2.     2.    -2.     3.   ]
 [ 0.     0.     1.     4.     3.5  ]
 [-0.    -0.    -0.     1.     0.875]] 
 Solución del sistema:
 [0.70833333 2.375      0.         0.875     ]


**2** Usando la rutina  `Gaussian_Elimination`, para crear una nueva rutina` Inverse` que calcule el inverso de cualquier matriz cuadrada dada. Luego use la rutina para enconcontrar la solucion de las matrices $M_1$ y $M_2$

In [46]:
def Esca_red(A0):           #Esta es una función para hallar la escalonada reducida aplicando Gauss-Jorda
    A = 1.0*np.copy(A0)     #Pues con solo la función escalonada no se puede hallar la inversa
    n = len(A)
                            #La mitad de la función es Gaussian_Elimination y la otra parte es para hallar los
                            #ceros sobre la diagonal                    
    for i in range(n):
        for j in range(i+1):
                if i==j:
                    if A[i,j]==0:               
                        A = row_swap(i, -1, A)
                    break
                A = row_comb(i, j, -A[i,j]/A[j,j], A)   
                 
    for i in range(n):                  
        for j in range(i+1):            
                if i==j:
                    if A[i,j]==0:
                        A = row_swap(i, -1, A)
                    break
                A = row_comb(i, j, -A[i,j]/A[j,j], A)  #Hasta aquí es la misma función que Gaussian_Elimination

    for i in range(0,n):      #con este for convierto toda la diagonal en 1
        for j in range(0,n):
            if i==j:
                A=row_lamb( i, 1.0/A[i,j], A )
        
    for k in range(n-1, 1, -1):   #Aquí vuelvo 0 todos los números arriba de la diagonal
        for i in range(n-1,-1,-1):
            for j in range(1, n-i):
                A = row_comb(i, i+j, -A[i, i+j], A)   
        A = row_lamb( i, 1.0/A[i,i], A )
    
    return A

###################################################################################################

def Inverse(A0):       #Función para hallar inversa
    A = 1.0*np.copy(A0)
    n = len(A)
    #Se debe revisar si la matriz es cuadrada
    if A.shape[0] == A.shape[1]:
        I = np.identity(n)
        #Aumento la matriz con la matriz identidad
        A = np.append(A, I, axis=1)
        #a la matriz aumentada le hago Gauss-Jordan 
        K = Esca_red(A)
        #Finalmente, de la matriz aumentada escalonada reducida, saco la matriz inversa 
        #que sería la segunda parte de la matriz
        j=int(K.shape[1]/2)
        Inv = K[:, j:]
    else:
        print('¡¡¡La matriz debe ser cuadrada!!!')
    return Inv

####################################################################################################

M1_ = np.delete(M1, -1, axis=1)         #Se sabe que x = A^-1 * b entonces se multiplica la inversa por b que es la parte
b1 = np.array([3, -4, 9])               #derecha de la igualdad

M2_ = np.delete(M2, -1, axis=1)
b2 = np.array( [1, 5, 6, 2])

Solu_M1 = np.dot(Inverse(M1_), b1)
Solu_M2 = np.dot(Inverse(M2_), b2)

print("La inversa de M1 es: \n {} \n Solución del sistema:\n {}".format( Inverse(M1_), Solu_M1 ))
print("La inversa de M2 es: \n {} \n Solución del sistema:\n {}".format( Inverse(M2_), Solu_M2 ))

La inversa de M1 es: 
 [[ 3.33333333 -1.66666667 -1.        ]
 [ 3.83333333 -2.16666667 -1.        ]
 [-3.16666667  1.83333333  1.        ]] 
 Solución del sistema:
 [ 7.66666667 11.16666667 -7.83333333]
La inversa de M2 es: 
 [[ -9.41666667   4.29166667  -1.58333333  -0.91666667]
 [-14.75         6.625       -2.25        -1.25      ]
 [ 11.          -5.           2.           1.        ]
 [ -2.75         1.125       -0.25        -0.25      ]] 
 Solución del sistema:
 [0.70833333 2.375      0.         0.875     ]


**3** Usando la rutina `Gaussian_Elimination` y rastreando las operaciones realizadas, construya una nueva rutina llamada` Gaussian_Determinant`. Calculo el determinante de las matrices $M_1$ y $M_2$ 

In [59]:
def Gauss_det(A0):      #Esta función hace eliminación gaussiana, pero le añadí que si se realiza un cambio de filas, 
                        #se multiplica la fila que se quiere cambiar por -1.
    A = 1.0*np.copy(A0)
    n=len(A)
    for i in range(n):
        for j in range(i+1):
                if i==j:
                    if A[i,j]==0:
                        A = row_swap(i, -1, A)
                        A = row_lamb(i+1, -1, A)   #En este punto me aseguro que al intercambiar filas, la fila cambiada 
                    break                          #se multiplique por -1, pues es una condición para hallar el determinante 
                                                   #usando la matriz escalonada.
                A = row_comb(i, j, -A[i,j]/A[j,j], A)
    for i in range(n):
        for j in range(i+1):
                if i==j:
                    if A[i,j]==0:
                        A = row_swap(i, -1, A)
                        A = row_lamb(i+1, -1, A)
                    break
                A = row_comb(i, j, -A[i,j]/A[j,j], A)
    return A

#######################################################################################################

def Gaussian_Determinant(A0):   #El determinante de una matriz (debe ser cuadrada) es el productor de los coeficientes de
    A=1.0*np.copy(A0)           #de la diagonal de la matriz triangular superior
    T=Gauss_det(A)
    if A.shape[0] == A.shape[1]:   
        n=len(A)
        D=1
        for i in range(n):
            for j in range(n):
                if i==j:
                    D=D*T[i,j]
    return D

print('Determinate de la matriz:\n', Gaussian_Determinant(M1_))
print('Determinate de la matriz:\n', Gaussian_Determinant(M2_))

Determinate de la matriz:
 -6.0
Determinate de la matriz:
 -24.0


## **4** Usando la funcion ` Gaussian_Determinant` encuentre la inversa de una matriz y luego encuentre la solucion de las matrices $M_1$ y $M_2$. 

**Nota** recuerde que la solucion de un sistema con el determinante se puede escribir como:
$$A^{-1}=\frac{1}{|A|} {\bf{Adj}}(A^T) $$
Por lo que debera creear una funcion que encuentre la ${Adj(A)}^T$

In [61]:
def Adjunta(A0):    #La adjunta de una matriz es una matriz de cofactores de la traspuesta de la matriz, por lo que 
    A=np.copy(A0)   #la entrada de la función es la matriz normal y dentro de la función Adjunta se convierte a traspuesta.
    AT=A.T
    if A.shape[0] == A.shape[1]:   #Asegurar que la matriz sea cuadrada
        n=len(A)
        Adj=np.zeros((n,n))        #Hacer matriz de ceros con la misma dimensión
        for i in range(n):
            for j in range(n):
                Ai=np.delete(AT, i, axis=0)    #Eliminar la fila i y la columna j de cada elemento de la matriz traspuesta
                Aj=np.delete(Ai, j, axis=1)
                k=Gaussian_Determinant(Aj)     #Hallar el determinante de la matriz n-1 x n-1
                if i%2 != 0:                   #Reemplazar cada determinante por el elemento i,j de la matriz de ceros.
                    if j%2==0:           
                        Adj[i,j]=-k            #Con estos ciclos se asegura que los signos sean correctos
                    else:
                        Adj[i,j]=k
                else:
                    if j%2!=0:
                        Adj[i,j]=-k
                    else:
                        Adj[i,j]=k
    else:
        print("¡La matriz debe ser cuadrada")
    return Adj

#########################################################################

def Inver(A0):
    A=1.0*np.copy(A0)
    Adjun = Adjunta(A)
    DetA = Gaussian_Determinant(A)
    Invers = Adjun/DetA
    return Invers
    
Sol_M1 = np.dot(Inver(M1_), b1)
Sol_M2 = np.dot(Inver(M2_), b2)


print("Matriz Adjunta:\n{} \n Matriz inversa de M1: \n {} \n Solución del sistema: \n {}\n".format(Adjunta(M1_), Inver(M1_), Sol_M1) )
print("Matriz Adjunta:\n{} \n Matriz inversa de M1: \n {} \n Solución del sistema: \n {}\n".format(Adjunta(M2_), Inver(M2_), Sol_M2) )

Matriz Adjunta:
[[-20.  10.   6.]
 [-23.  13.   6.]
 [ 19. -11.  -6.]] 
 Matriz inversa de M1: 
 [[ 3.33333333 -1.66666667 -1.        ]
 [ 3.83333333 -2.16666667 -1.        ]
 [-3.16666667  1.83333333  1.        ]] 
 Solución del sistema: 
 [ 7.66666667 11.16666667 -7.83333333]

Matriz Adjunta:
[[ 226. -103.   38.   22.]
 [ 354. -159.   54.   30.]
 [-264.  120.  -48.  -24.]
 [  66.  -27.    6.    6.]] 
 Matriz inversa de M1: 
 [[ -9.41666667   4.29166667  -1.58333333  -0.91666667]
 [-14.75         6.625       -2.25        -1.25      ]
 [ 11.          -5.           2.           1.        ]
 [ -2.75         1.125       -0.25        -0.25      ]] 
 Solución del sistema: 
 [0.70833333 2.375      0.         0.875     ]



**5** Cree una rutina llamada `LU_Factorization` que, dada una matriz $ \mathbf {A} $ y el algoritmo anterior, calcule la factorización LU de la matriz. Pruebe su rutina con las matrices cuadrada $M_1$ y $M_2$, verifique que $ \mathbf {A} = \mathbf {L} \mathbf {U} $ sean las ya dadas y encuentre la solucion a estas matices $M_1$ y $M_2$.

In [86]:
def LU(A0):
    A=np.copy(A0)
    n=len(A)
    U=Gaussian_Elimination(A)
    
    
    
    
    
    
    
    return U

In [87]:
LU(M1_)

array([[ 2.,  1.,  3.],
       [ 0., -3., -3.],
       [ 0.,  0.,  1.]])